-- Special Budget INSERT Statements
-- budget_id starts from 565, fiscalyear changed to 2026

INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (565, 2026, '특별(Special)', 9020, '9020 강단미화헌금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (566, 2026, '특별(Special)', 9025, '9025 Summer Camp', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (567, 2026, '특별(Special)', 9026, '9026 Central Music Academy', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (568, 2026, '특별(Special)', 9027, '9027 DC Campus', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (569, 2026, '특별(Special)', 9030, '9030 선교사자녀장학기금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (570, 2026, '특별(Special)', 9031, '9031 해돋이 장학금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (571, 2026, '특별(Special)', 9035, '9035 일반장학금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (572, 2026, '특별(Special)', 9050, '9050 STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (573, 2026, '특별(Special)', 9051, '9051 JG STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (574, 2026, '특별(Special)', 9052, '9052 AGAPE STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (575, 2026, '특별(Special)', 9053, '9053 ALL STARS STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (576, 2026, '특별(Special)', 9054, '9054 KINGDOM STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (577, 2026, '특별(Special)', 9055, '9055 SOJOURN STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (578, 2026, '특별(Special)', 9056, '9056 DASOM STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (579, 2026, '특별(Special)', 9057, '9057 EC STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (580, 2026, '특별(Special)', 9058, '9058 DC CAMPUS STM', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (581, 2026, '특별(Special)', 9060, '9060 개인지정선교헌금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (582, 2026, '특별(Special)', 9080, '9080 순모임선교헌금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (583, 2026, '특별(Special)', 9120, '9120 신학생장학기금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (584, 2026, '특별(Special)', 9140, '9140 북한선교', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (585, 2026, '특별(Special)', 9160, '9160 COUNSELING OFFICE', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (586, 2026, '특별(Special)', 9190, '9190 CULPEPER', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (587, 2026, '특별(Special)', 9500, '9500 SPECIAL CONTRIBUITONS', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (588, 2026, '특별(Special)', 9510, '9510 경로잔치', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (589, 2026, '특별(Special)', 9550, '9550 DTS Fund', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (590, 2026, '특별(Special)', 9650, '9650 제3권사회', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (591, 2026, '특별(Special)', 9670, '9670 Women''s Ministry', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (592, 2026, '특별(Special)', 9800, '9800 VISION 123 CONTRIBUTION', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (593, 2026, '특별(Special)', 9860, '9860 VISION 123 비품헌금기금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (594, 2026, '특별(Special)', 8000, '8000 교직원연금', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (595, 2026, '특별(Special)', 8300, '8300 RELIEF FUND', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (596, 2026, '특별(Special)', 8400, '8400 SPECIAL RESERVE', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (597, 2026, '특별(Special)', 8450, '8450 STM Support', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (598, 2026, '특별(Special)', 8500, '8500 NEW CHURCH OPERATING RESERVE', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (599, 2026, '특별(Special)', 8600, '8600 VISON 건축 RESERVE', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (600, 2026, '특별(Special)', 8800, '8800 INTERN PASTOR SCHOLARSHIP', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (601, 2026, '특별(Special)', 3110, '3110 DF-Intern Pastor Scholarship', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (602, 2026, '특별(Special)', 3120, '3120 DF-Mission Fundraisers', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (603, 2026, '특별(Special)', 3130, '3130 DF-Operating Reserve', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (604, 2026, '특별(Special)', 3140, '3140 DF-Planning Committee', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (605, 2026, '특별(Special)', 3160, '3160 DF-Special Project Reserve', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (606, 2026, '특별(Special)', 3170, '3170 DF-Staff Pension', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (607, 2026, '특별(Special)', 3180, '3180 DF-Vision 123 Equip Reserve', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (608, 2026, '특별(Special)', 3190, '3190 DF-Vision 123 Reserve', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (609, 2026, '특별(Special)', 3300, '3300 TR-2 Kwonsa Group', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (610, 2026, '특별(Special)', 3310, '3310 TR-3 Kwonsa Group', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (611, 2026, '특별(Special)', 3320, '3320 TR-Cont for aged-Yng men gr', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (612, 2026, '특별(Special)', 3330, '3330 TR-Counseling Operation', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (613, 2026, '특별(Special)', 3340, '3340 TR-Culpepper', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (614, 2026, '특별(Special)', 3350, '3350 TR-Disciple Training', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (615, 2026, '특별(Special)', 3360, '3360 TR-DTS', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (616, 2026, '특별(Special)', 3370, '3370 TR-ED Vision-Agape', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (617, 2026, '특별(Special)', 3380, '3380 TR-ED Vision-All Star(Jr High)', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (618, 2026, '특별(Special)', 3390, '3390 TR-ED Vision-JG(Sr. High)', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (619, 2026, '특별(Special)', 3400, '3400 TR-ED Vision-Promiseland', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (620, 2026, '특별(Special)', 3410, '3410 TR-Fellowship (Donuts/Coffee)', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (621, 2026, '특별(Special)', 3420, '3420 TR-Fellowship (Meals)', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (622, 2026, '특별(Special)', 3430, '3430 TR-Flowers', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (623, 2026, '특별(Special)', 3440, '3440 TR-General Scholarship', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (624, 2026, '특별(Special)', 3450, '3450 TR-HanDong Univ.', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (625, 2026, '특별(Special)', 3460, '3460 TR-Ind Designated Miss', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (626, 2026, '특별(Special)', 3470, '3470 TR-KCPC Central Music Academy', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (627, 2026, '특별(Special)', 3480, '3480 TR-Library Fund', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (628, 2026, '특별(Special)', 3490, '3490 TR-Missionary Scholarship', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (629, 2026, '특별(Special)', 3500, '3500 TR-New Church Equipment Fund', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (630, 2026, '특별(Special)', 3510, '3510 TR-New Year Fasting Service', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (631, 2026, '특별(Special)', 3520, '3520 TR-North Korea Miss', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (632, 2026, '특별(Special)', 3530, '3530 TR-Rising Sun Scholarship', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (633, 2026, '특별(Special)', 3540, '3540 TR-Salt & Light Ministry', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (634, 2026, '특별(Special)', 3550, '3550 TR-Seminary Sch', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (635, 2026, '특별(Special)', 3560, '3560 TR-Senior Ministry', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (636, 2026, '특별(Special)', 3570, '3570 TR-Senior Party', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (637, 2026, '특별(Special)', 3580, '3580 TR-Short Term Mission', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (638, 2026, '특별(Special)', 3590, '3590 TR-Small Grp Mission Offering', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (639, 2026, '특별(Special)', 3600, '3600 TR-Special Cont- Thanksgiving', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (640, 2026, '특별(Special)', 3610, '3610 TR-Special Cont.- Temp Holding', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (641, 2026, '특별(Special)', 3620, '3620 TR-State Beautification', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (642, 2026, '특별(Special)', 3630, '3630 TR-Summer Camp', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (643, 2026, '특별(Special)', 3640, '3640 TR-VBS', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (644, 2026, '특별(Special)', 3650, '3650 TR-Vision 123 Contributions', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (645, 2026, '특별(Special)', 3660, '3660 TR-Vision 123 Moving Prep Fund', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (646, 2026, '특별(Special)', 3670, '3670 TR-Wedd Spc Miss', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (647, 2026, '특별(Special)', 3680, '3680 TR-Women''s Ministry', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (648, 2026, '특별(Special)', 3690, '3690 TR-Youth Camp-Agape', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (649, 2026, '특별(Special)', 3700, '3700 TR-Youth Camp-Jr. High', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (650, 2026, '특별(Special)', 3710, '3710 TR-Youth Camp-Sr. High', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (651, 2026, '특별(Special)', 3711, '3711 Allocate Fund - Fund Balance', NULL, NULL);
INSERT INTO public.org_budget (budget_id, fiscalyear, sayuk_name, budget_code, budget_name, "gl name", budget_amount) VALUES (652, 2026, '특별(Special)', 3150, '3150 DF-Relief Fund', NULL, NULL);